In [6]:
import numpy as np

from sys import getsizeof

#1 : create matrix 3x3
a = np.zeros((3,3))

print(a)

a = np.random.randint(0,10, size=(3,3))
print(a)

a.ndim

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[6 1 2]
 [7 8 8]
 [0 9 2]]


2

In [8]:
#2 : check if any element is not 0

(a==0).any()

True

In [17]:
# 3 : 

# ten numbers 0
a  = np.zeros(10)
print(a)

# ten numbers 1
b = np.ones(10)
print(b)

# ten numbers 5
c = np.full(10,5)
print(c)


[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[5 5 5 5 5 5 5 5 5 5]


In [22]:
#4 : so nguyen chan tu 30 den 70

a = np.arange(30,72,2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [37]:
#5: save numpy array to binary file

from tempfile import TemporaryFile
outfile = TemporaryFile()

a = np.arange(0,10)
np.save(outfile,a)

outfile.seek(0)
np.load(outfile)


TypeError: save() missing 1 required positional argument: 'arr'

In [39]:
#6 : ma tran zero 5x5, phan tu tren duong cheo bang 1 -> 5

diag = np.arange(1,6)

a = np.diagflat(diag)
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [69]:
#7 : save array to file
a = np.arange(1,10)
a = a.reshape(3,3)

np.savetxt("test.txt", a, "%d", delimiter=",")

b = np.loadtxt("test.txt", delimiter=",")
b

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [65]:
x = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]], np.int32)
np.savetxt("test2.txt", x, fmt="%2.3f", delimiter=",")


In [ ]:
# 8 : 