In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sbn
from datetime import datetime
from numpy.linalg import inv
from numpy.linalg import norm

In [2]:
# sigmoid function
def sigmoid(z):
    return 1 / (1+np.exp(-z))

In [47]:
X = np.array([[1,2], [3,4], [5,6]])
y = np.array([7,8,9])

print(X,y)

[[1 2]
 [3 4]
 [5 6]] [7 8 9]


In [77]:
# cost function, return cost and gradient value
def cost(theta, X, y):
    N = len(y)
    
    print(X.shape)
    h = sigmoid(np.dot(X, theta))

    # cost
    J = np.dot(y, np.log(h)) + np.dot( (1-y), np.log(1-h) )
    J = -J/N
    
    # gradient
    #dJ   = np.dot(X.T, (h - y)) / N
    dJ   = (X.T @ (h - y)) / N
    
    # hessian
    Hess = (X.T @ np.diag(h) @ np.diag(1-h) @ X) / N
    
    return J, dJ, Hess

In [5]:
# gradient function
def grad(theta, X, y):
    N = len(y)
    
    h = sigmoid(np.dot(X, theta))
    
    
    
    return dJ, Hess
    

In [79]:
#c,g,H = cost(np.array([0,0]), X, y)

#print(H)

#print(np.dot(inv(H), g))

#print(inv(H) @ g)

#theta = [0,0] - (inv(H) @ g)
a = np.insert(X, 0, values=1, axis=1)
print(a)

theta = [0, 0, 0]
for i in np.arange(2):
    print("Iter ",i)
    c,g,H = cost(theta, a, y)
    print("Hessian:", H)
    theta = theta - (inv(H) @ g)
    print("theta:", theta)

[[1 1 2]
 [1 3 4]
 [1 5 6]]
Iter  0
(3, 3)
Hessian: [[0.25       0.75       1.        ]
 [0.75       2.91666667 3.66666667]
 [1.         3.66666667 4.66666667]]
theta: [192. -32. -32.]
Iter  1
(3, 3)
Hessian: [[4.22138852e-15 1.26641655e-14 1.68855541e-14]
 [1.26641655e-14 3.79924966e-14 5.06566622e-14]
 [1.68855541e-14 5.06566622e-14 6.75422163e-14]]


/home/dmduc/installs/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


LinAlgError: Singular matrix

In [ ]:
# training with Newton method
def myGD_Newton(theta_init, grad, t, X, y,  iterations):
    start_time = datetime.now()
    
    cost_array = []
    theta_array = [theta_init]
    
    for it in range( iterations): # so buoc lap toi da
        
        # cost, gradient, hessian
        c, g, H = cost(theta_array[-1], X, y)
        
        # check stop condition, if not satisfy, update theta
        if (norm(g)/len(theta_array[-1])) < 1e-3:
        #if (np.linalg.norm(gradient_current)) < 1e-3:
            break
        
        #theta_new = theta_array[-1] - t*gradient_current
        theta_new = theta_array[-1] - (inv(H) @ g)
        
        theta_array.append(theta_new)
        cost_array.append(c)        
        
    print(f'Running time with Gradient Descent: {datetime.now() - start_time}')
    return (theta_array, it)

In [ ]:
# Lam viec voi du lieu data1
df1 = pd.read_csv("voice.csv").values
print(df1.shape)
X1=df1[:,0:20]
y1=df1[:,20]
N = df1.shape[0]
print(N)

X1 = np.array(X1, dtype=np.float64)
mean = X1.mean(axis = 0)
std = X1.std(axis = 0)
X1 = (X1 - mean)/std
X1 = np.hstack((np.ones((N, 1)), X1))
D1 = X1.shape[1]
print(D1)

## Khoi tao cac gia tri
theta_init = np.zeros(D1).T # khoi tao gia tri anpha
t_init = 0.1
beta = 0.5
alpha = 0.5
iterations =1000


In [ ]:
################ chay thuat toan GD
(theta, it) = myGD_Newton(theta_init, grad, t_init, X1, y1,  iterations) ## cho gia tri t=1 hoac 1/2 
print('Thuat toan gradient descent:', theta[-1])
print('So buoc lap: ',it)


In [ ]:
################ chay thuat toan GD Newton method
(theta, it) = myGD_Newton(theta_init, grad, t_init, X1, y1,  iterations) ## cho gia tri t=1 hoac 1/2 
print('Thuat toan gradient descent:', theta[-1])
print('So buoc lap: ',it)
